export enum APP_ACTIONS {
  ENABLE_DARK_MODE = "ENABLE_DARK_MODE",
  BYPASS_LOGIN_BECAUSE_IN_DEV_MODE = "BYPASS_LOGIN_BECAUSE_IN_DEV_MODE",
}

export enum THEMES {
  LIGHT = "LIGHT",
  DARK = "DARK",
  NATURE = "NATURE",
}