export enum CART_ACTIONS {
    ADD_PRODUCT = "ADD_PRODUCT",
    REMOVE_PRODUCT = "REMOVE_PRODUCT",
    SAVE_CART_SNAPSHOT = "SAVE_CART_SNAPSHOT",
    RESTORE_CART_SNAPSHOT = "RESTORE_CART_SNAPSHOT",
    CLEAR_CART = "CLEAR_CART",
}
